/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package partychat;

public class App {
    public static void main(String[] args) {
        MainWindow mainobj = new MainWindow();
        mainobj.start();
    }
}
